### ISSUE TITLE
[Feature] Distance: we don't need decimal precision

### ISSUE THREAD

**Issue by Nickduino** [ngocjohn/lunar-phase-card#30]
### Short summary

Displaying 400 309 km would look better than 400 309,66km

### Detailed description

I appreciate the fact we can display the distance (and that there is an option to show miles - even though the doc doesn't mention it yet), that's fun to check. But having it precise to 10 meters doesn't seem necessary to me.

Could you add an option to drop the decimals?
(Or possibly drop them by default? Or at least put a space between the second decimal place and the k of km to make it more readable?)

### Examples 🖼️

From:
![image](https://github.com/user-attachments/assets/3e15a82a-dae4-4507-80f1-3fe90dc79fc1)

To:
![image](https://github.com/user-attachments/assets/35b8d6a3-84d4-4874-9e54-04f4d095f566)

Or, at the very least:
![image](https://github.com/user-attachments/assets/08c4edbd-91d9-483c-9559-ead15068c0a2)

**Comment by ngocjohn** [comment]
Hi @Nickduino, I have modified the unit display style according to the selected language, uploaded a new version to the release. For the fixes version please redownload via HACS, and select the same version and hard reload the browser. 

I will try to figure out something with the decimal option, because the values with decimal are also for different info and it is invidual for each user differently. 

![CleanShot 2024-11-02 at 18 00 57@2x](https://github.com/user-attachments/assets/98e4bcaf-28c0-4760-9d69-aaa6f8649215)

**Comment by ngocjohn** [comment]
Hi @Nickduino, small update, the last version 1.7.2 added the ability to set decimals. 🎉
